version: "3.9"

services:
  gorzdrav-parser:
    build: .
    container_name: gorzdrav-parser
    ports:
      - "8003:8000"
    restart: always
    networks:
      - parser-network

networks:
  parser-network:
    external: true
